version: "3.1"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    networks:
      - system-recommendation

networks:
  system-recommendation:
    driver: bridge
