services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    env_file:
      - "./.env.prod"
    networks:
      - recfoodcato-networks

networks:
  recfoodcato-networks:
    driver: bridge
