version: "3.1"

services:
  frontend:
    build:
      dockerfile: ./Dockerfile
    expose:
      - 3005:3000
    networks:
      - system-recomendation

networks:
  system-recomendation:
    - driver: bridge
