services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.1.3:8090
    networks:
      - recfoodcato-networks

networks:
  recfoodcato-networks:
    driver: bridge
