version: "3.1"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    networks:
      - recfoodcato-networks

networks:
  recfoodcato-networks:
    driver: bridge
